"""Edit user model:change location field to school.

Revision ID: 0512be2c4dd0
Revises: 46c1162238a6
Create Date: 2017-09-27 15:34:22.537431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0512be2c4dd0'
down_revision = '46c1162238a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=64), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('school')

    # ### end Alembic commands ###
