"""Add avatar_hash

Revision ID: 212b6aa5ae84
Revises: 1f3a2d12c0ef
Create Date: 2017-09-05 10:22:29.868629

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '212b6aa5ae84'
down_revision = '1f3a2d12c0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
