"""add invitation-code Model.

Revision ID: 2e6411c59838
Revises: 8bfc5223c9dd
Create Date: 2017-10-05 19:02:29.359775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6411c59838'
down_revision = '8bfc5223c9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitationcodes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_unique_constraint("code", ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitationcodes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
