"""Recover write permission for User role

Revision ID: 30c9138da49b
Revises: 65b6047b5b2f
Create Date: 2017-10-01 19:17:45.408963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c9138da49b'
down_revision = '65b6047b5b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
