"""增加订单表，用户支付以后查询该订单是否存在且已支付

Revision ID: 421c8d73c653
Revises: cfef0d11c95c
Create Date: 2017-10-24 22:14:39.344556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421c8d73c653'
down_revision = 'cfef0d11c95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_email'))

    op.drop_table('orders')
    # ### end Alembic commands ###
