"""Add read and like times.

Revision ID: 46c1162238a6
Revises: 2d02f4865b31
Create Date: 2017-09-23 11:17:26.911209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c1162238a6'
down_revision = '2d02f4865b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_times', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('read_times', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('read_times')
        batch_op.drop_column('like_times')

    # ### end Alembic commands ###
