"""add invitation-code Model.

Revision ID: 50e389bbbe6d
Revises: 6c6f8b0c361f
Create Date: 2017-10-05 19:18:49.418184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e389bbbe6d'
down_revision = '6c6f8b0c361f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitationcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitationcodes')
    # ### end Alembic commands ###
