"""Add confired column

Revision ID: 546eb60f83b9
Revises: 
Create Date: 2017-08-27 14:16:51.729484

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '546eb60f83b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
