"""Add body_html field

Revision ID: 5788d1b826ee
Revises: c01dc7e527a8
Create Date: 2017-09-10 10:56:58.896773

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5788d1b826ee'
down_revision = 'c01dc7e527a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body_html')
    # ### end Alembic commands ###
