"""Edit user model,add school and major field 

Revision ID: 65b6047b5b2f
Revises: 0512be2c4dd0
Create Date: 2017-09-27 16:00:20.037489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b6047b5b2f'
down_revision = '0512be2c4dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('major')

    # ### end Alembic commands ###
