"""alter post table:add body_abstract field

Revision ID: 83e7b152e3f1
Revises: 5de2cbc0b77e
Create Date: 2017-10-18 20:05:55.037865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e7b152e3f1'
down_revision = '5de2cbc0b77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_abstract', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body_abstract')

    # ### end Alembic commands ###
