"""add invitation-code Model.

Revision ID: 8bfc5223c9dd
Revises: f49b6cf93e67
Create Date: 2017-10-05 18:55:53.211605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfc5223c9dd'
down_revision = 'f49b6cf93e67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitationcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitationcodes')
    # ### end Alembic commands ###
