"""Alter database:add score Table

Revision ID: 8d7f15d0ed6b
Revises: 30c9138da49b
Create Date: 2017-10-02 12:08:57.315780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7f15d0ed6b'
down_revision = '30c9138da49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.Column('year_2017', sa.Integer(), nullable=True),
    sa.Column('year_2015', sa.Integer(), nullable=True),
    sa.Column('year_2014', sa.Integer(), nullable=True),
    sa.Column('year_2013', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    # ### end Alembic commands ###
