"""add invitation-code Model.

Revision ID: cf6a84695ed8
Revises: 2e6411c59838
Create Date: 2017-10-05 19:10:35.977346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6a84695ed8'
down_revision = '2e6411c59838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitationcodes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitationcodes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
