"""add score column of 2016y.

Revision ID: f49b6cf93e67
Revises: fbcba72a119d
Create Date: 2017-10-03 11:05:04.821349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49b6cf93e67'
down_revision = 'fbcba72a119d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_2016', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('year_2016')

    # ### end Alembic commands ###
